ToDoProject/Accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', view=auth_views.LoginView.as_view(
        template_name="Accounts/login.html",
        redirect_authenticated_user=True,
    ), name="login"),
    path('logout/', view=auth_views.LogoutView.as_view(
        template_name="Accounts/logout.html",
    ), name="logout"),
    path('signup/', view=views.register, name="signup"),
]

ToDoProject/Main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('index/', view=views.index, name="index"),
    path('add_work/', view=views.CreateWork.as_view(), name="add_work"),
    path('work_list/', view=views.WorkList.as_view(), name="work_list"),
    path('work/<int:pk>/update/', view=views.WorkUpdate.as_view(), name='work_update'),
    path('work/<int:pk>/delete/', view=views.WorkDelete.as_view(), name='work_delete'),
]

ToDoProject/ToDoProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('', include('Main.urls')),
]

ToDoProject/Accounts/models.py
from django.db import models

# Create your models here.

ToDoProject/Main/models.py
from email.policy import default
from random import choices
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Work(models.Model):
    LOW = 0
    NORMAL = 1
    HIGH = 2
    FHIGH = 3
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)
    date_created = models.DateTimeField(default=timezone.now)
    complete_till = models.DateTimeField(default=timezone.now)
    is_completed = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    priority = models.IntegerField(choices=(
        (LOW, 'LOW'),
        (NORMAL, 'NORMAL'),
        (HIGH, 'HIGH'),
        (FHIGH, 'FIRST PRIORITY'),
    ), default=2)

    class Meta:
        ordering = ['-priority', '-date_created']

    def __str__(self):
        return self.title

    @property
    def are_you_late(self):
        if self.complete_till < timezone.now():
            return True
        return False

ToDoProject/Accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

ToDoProject/Accounts/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import UserRegistrationForm

# Create your views here.
def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, message=f"Account created for {username}!")
            return redirect('accounts:login')
    else:
        form = UserRegistrationForm()
    return render(request, template_name="Accounts/register.html", context={
        "form": form,
    })

ToDoProject/Main/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from .models import Work

# Create your views here.
@login_required
def index(request):
    total_completed = Work.objects.filter(author=request.user, is_completed=True).count()
    total = Work.objects.filter(author=request.user).count()
    return render(request, template_name="Main/index.html", context={
        "total_completed": total_completed,
        "total": total,
        "not_completed": total - total_completed,
    })


class CreateWork(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Work
    fields = ['title', 'description', 'priority', 'complete_till', 'is_completed']
    template_name = "Main/add_work.html"
    success_message = "Work was added successfully"

    def get_success_url(self) -> str:
        return reverse("main:work_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class WorkList(LoginRequiredMixin, ListView):
    model = Work
    template_name = "Main/worklist.html"
    paginate_by = 25

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)       

class WorkUpdate(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    model = Work
    template_name = "Main/updatework.html"
    fields = ['title', 'description', 'priority', 'complete_till', 'is_completed']
    success_message = "Work was updated successfully"
    
    def get_success_url(self):
        return reverse("main:work_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class WorkDelete(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin, DeleteView):
    model = Work
    success_message = "Work was deleted successfully"

    def get_success_url(self):
        return reverse("main:work_list")

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

ToDoProject/Accounts/templates/Accounts/login.html
{% extends 'Main/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'accounts:signup' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

ToDoProject/Accounts/templates/Accounts/logout.html
{% extends 'Main/base.html' %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'accounts:login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

ToDoProject/Accounts/templates/Accounts/register.html
{% extends 'Main/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'accounts:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}

ToDoProject/Main/templates/Main/add_work.html
{% extends 'Main/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Work</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Add</button>
        </div>
    </form>
</div>
{% endblock %}

ToDoProject/Main/templates/Main/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'Main/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'Main/main.css' %}">
    {% if title %}
        <title>PriorWork - {{ title }}</title>
    {% else %}
        <title>PriorWork</title>
    {% endif %}
    {% block head %}
    {% endblock %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="">PriorWork</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'main:index' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'main:add_work' %}">Add Work</a>
                <a class="nav-item nav-link" href="{% url 'main:work_list' %}">Work List</a>
                <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>Recent information.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                  <h4>Go through this works</h4>
                  {% for work in user.work_set.all|slice:":5"  %}
                    <a href="{% url 'main:work_update' work.pk %}" class="link-primary">{{work.title}}</a><br/>
                  {% endfor %}
                </li>
                <!-- <li class="list-group-item list-group-item-light">
                  {{ user.work_set }}
                </li> -->
                <li class="list-group-item list-group-item-light">
                  Total Works: {{ user.work_set.count }}
                </li>                
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="{% static jquery.min.js %}"></script>  
    <script src="{% static bootstrap.min.js %}"></script>
    <script src="{% static popper.min.js %}"></script>   -->
</body>
</html>

ToDoProject/Main/templates/Main/index.html
{% extends 'Main/base.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'Main/chart.js' %}"></script>
{% endblock %}
{% block content %}
    <h3>Welcome {{ user.username.title }}!</h3>
    <p>This is a very simple website to keep track of work/task you need to complete. Here you can keep record of what work/task you have to do and what you have completed, you can also specify time at which the work needed to be completed. So keep your work on PriorWork</p>
    <canvas id="pie-chart" style="width:100%;max-width:600px"></canvas>
    <script>
        var xValues = ["Total", "Completed", "Not Completed"];
        var yValues = [{{ total }}, {{ total_completed }}, {{ not_completed }}];
        var barColors = [
          "#00aba9",
          "#1e7145",
          "#b91d47",
        ];
        
        new Chart("pie-chart", {
          type: "pie",
          data: {
            labels: xValues,
            datasets: [{
              backgroundColor: barColors,
              data: yValues
            }]
          },
          options: {
            title: {
              display: true,
              text: "Your Progress"
            }
          }
        });
        </script>
{% endblock %}

ToDoProject/Main/templates/Main/updatework.html
{% extends 'Main/base.html' %}
{% load crispy_forms_tags %}
{% block content %}    
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ work.title }}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'main:work_delete' work.id %}">Delete</a>
            </div>
        </form>
    </div>
    <a class="btn btn-outline-secondary" href="{% url 'main:work_list' %}">Back</a>
{% endblock %}

ToDoProject/Main/templates/Main/work_confirm_delete.html
{% extends "main/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'main:work_update' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

ToDoProject/Main/templates/Main/worklist.html
{% extends 'Main/base.html' %}
{% block content %}

<h3> Work List</h3>

{% if not page_obj %}
    <p>No work is added yet, please add work <a href="{% url 'main:add_work' %}">here</a></p>
{% endif %}
    <div class="list-group">
        {% for work in page_obj %}
            <a href="{% url 'main:work_update' work.pk %}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    {% if work.is_completed %}
                        <h5 class="mb-1"><s>{{ work.title }}</s></h5>
                    {% else %}
                        <h5 class="mb-1">{{ work.title }}</h5>
                    {% endif %}
                    <small>{{ work.date_created }}</small>
                </div>
                <p class="mb-1" style="white-space: pre-line;">{{ work.description }}</p>
                {% if work.is_completed %}
                    <span class="badge bg-success">Completed</span>
                {% else %}
                    <span class="badge bg-warning text-dark">Not Completed</span>
                    {% if work.are_you_late %}
                        <span class="badge bg-warning text-dark">{{ work.complete_till }}</span>
                        <span class="badge bg-danger">Not Completed On Time</span>
                    {% else %}
                        <span class="badge bg-warning text-dark">{{ work.complete_till }}</span>
                    {% endif %}
                {% endif %}
                <span class="badge bg-info">{{work.priority}}</span>
            </a>
        {% endfor %}
    </div>

    <br>
    {% if page_obj %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">First</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}        
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Previous">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="sr-only">Last</span>
                    </a>
                  </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}    
{% endblock %}